### ISSUE TITLE
Desktop : Home Page : Client Logos 

### ISSUE THREAD

**Issue by jimmyjacobson** [csbryan-resuce-vessel/lavender-lilly#2]
Logos are crowded at bottom of home page.

<img width="990" alt="Screen Shot 2020-04-21 at 9 41 58 AM" src="https://user-images.githubusercontent.com/451248/79890505-70eaa800-83b4-11ea-9e4b-71d6a467d784.png">

**Comment by csbryan-resuce-vessel** [comment]
Added some padding between icons and shifts down to two columns on small screens.
