### ISSUE TITLE
Mobile : Responsive Layout : All Pages

### ISSUE THREAD

**Issue by jimmyjacobson** [csbryan-resuce-vessel/lavender-lilly#3]
Pawel reported this one in Slack.

https://codingscape.slack.com/archives/C0116R8SH7W/p1587430579014700

![image](https://user-images.githubusercontent.com/451248/79890700-bad38e00-83b4-11ea-8341-82844d8f1603.png)

**Comment by csbryan-resuce-vessel** [comment]
Fix pushed for mobile styles.
