### ISSUE TITLE
Optimize Images : Carousel : About Page

### ISSUE THREAD

**Issue by jimmyjacobson** [csbryan-resuce-vessel/lavender-lilly#4]
The About page carousel slider images are coming in around 3 MB each.

**Comment by csbryan-resuce-vessel** [comment]
I noticed this. Im switching us pigs instead of svgs. There’s already a gatsby plungin that optimizes images but it doesn’t work with svgs.

**Comment by csbryan-resuce-vessel** [comment]
Switched out the largest images to png and used the gatsby sharp plugin on them.
